export const defaultSiteConfig = {
  images: {
    logo: '/assets/brand-logo.jpeg',
    ambience: '/assets/ambience1.jpeg',
    menuCard: '/assets/tiffins-menu.jpg',
    heroBg: '/assets/homepage-full.png',
    meals: ['/assets/tiffins-menu.jpg', '/assets/optimized-homepage.png', '/assets/homepage-screenshot.png'],
    biryani: '/assets/gallery-section.png',
    dosa: '/assets/reservation-section.png',
    idli: '/assets/ambience1.jpeg',
    curry: '/assets/homepage-mobile.png',
    dessert: '/assets/optimized-homepage.png',
    beverages: '/assets/tiffins-menu.jpg',
    interiors: ['/assets/ambience1.jpeg', '/assets/reservation-section.png', '/assets/homepage-full.png'],
    gallery: {
      food: ['/assets/tiffins-menu.jpg', '/assets/optimized-homepage.png', '/assets/homepage-screenshot.png', '/assets/homepage-mobile.png', '/assets/gallery-section.png', '/assets/reservation-section.png'],
      restaurant: ['/assets/ambience1.jpeg', '/assets/homepage-full.png', '/assets/optimized-homepage.png'],
      kitchen: ['/assets/reservation-section.png', '/assets/homepage-mobile.png'],
    },
    instagram: ['/assets/tiffins-menu.jpg', '/assets/optimized-homepage.png', '/assets/homepage-screenshot.png', '/assets/homepage-mobile.png', '/assets/gallery-section.png', '/assets/reservation-section.png'],
  },
  footerLinks: {
    quickLinks: [
      { label: 'Home', href: '#home' },
      { label: 'About Us', href: '#about' },
      { label: 'Our Menu', href: '#menu' },
      { label: 'Gallery', href: '#gallery' },
      { label: 'Reservations', href: '#reservation' },
      { label: 'Contact', href: '#contact' },
    ],
    hours: {
      weekdays: '11:00 AM – 3:00 PM, 6:00 PM – 10:30 PM',
      weekends: '10:00 AM – 11:00 PM',
      closedOn: 'No weekly off — open 365 days',
    },
    contact: {
      address: '12-3-456, Main Road, Kukatpally, Hyderabad, Telangana 500085',
      phone: '+91 98765 43210',
      email: 'hello@palleaathidhyam.com',
      mapEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3805.0254209415!2d78.3809941!3d17.5062999!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bcb91005f859e41%3A0xc3359ba69c3f6184!2sPALLE+AATHIDHYAM!5e0!3m2!1sen!2sin!4v1710000000000!5m2!1sen!2sin',
    },
    social: {
      instagram: 'https://www.instagram.com/palle_aathidhyam/',
      facebook: 'https://facebook.com/palleaathidhyam',
      youtube: 'https://youtube.com/@palleaathidhyam',
      twitter: 'https://twitter.com/palleaathidhyam',
    },
  },
  restaurantInfo: {
    name: 'Palle Aathidhyam',
    tagline: 'పల్లె ఆతిథ్యం — The Village Feast',
    description: 'Experience the authentic flavours of rural Telugu cuisine, handcrafted with love using age-old recipes and farm-fresh ingredients.',
    foundedYear: 2020,
  },
  ctaText: {
    heading: 'Reserve Your Table Today',
    subheading: 'Join us for an unforgettable culinary journey through the heartlands of Telangana and Andhra Pradesh.',
    buttonText: 'Book a Table',
    buttonHref: '#reservation',
  },
  menuItems: [
    {
      id: 'bk-01',
      name: 'పొంగలి (Pongali)',
      description: 'Creamy rice and moong dal tempered with ghee, cumin, pepper and cashews — a classic temple-style breakfast.',
      price: 100,
      category: 'breakfast',
      image: '/assets/ambience1.jpeg',
      isVeg: true,
      isSpicy: false,
      isPopular: true,
      isChefSpecial: false,
    },
    {
      id: 'bk-02',
      name: 'ఉప్మా (Upma)',
      description: 'Savoury semolina porridge studded with mustard seeds, urad dal, curry leaves and freshly grated coconut.',
      price: 80,
      category: 'breakfast',
      image: '/assets/tiffins-menu.jpg',
      isVeg: true,
      isSpicy: false,
      isPopular: false,
      isChefSpecial: false,
    },
    {
      id: 'bk-03',
      name: 'మసాలా దోస (Masala Dosa)',
      description: 'Crispy golden crepe filled with spiced potato masala, served with coconut chutney and sambar.',
      price: 120,
      category: 'breakfast',
      image: '/assets/reservation-section.png',
      isVeg: true,
      isSpicy: false,
      isPopular: true,
      isChefSpecial: false,
    },
    {
      id: 'bk-04',
      name: 'ఇడ్లీ వడ (Idli Vada)',
      description: 'Steamed rice cakes and crispy urad dal fritters served with a trio of chutneys and piping-hot sambar.',
      price: 110,
      category: 'breakfast',
      image: '/assets/ambience1.jpeg',
      isVeg: true,
      isSpicy: false,
      isPopular: true,
      isChefSpecial: false,
    },
    {
      id: 'bk-05',
      name: 'పూరి (Puri)',
      description: 'Puffed golden puris with a bowl of aromatic potato kurma and tangy tomato chutney.',
      price: 130,
      category: 'breakfast',
      image: '/assets/homepage-mobile.png',
      isVeg: true,
      isSpicy: true,
      isPopular: false,
      isChefSpecial: true,
    },
    {
      id: 'ml-01',
      name: 'వేగ భోజనం (Veg Meals)',
      description: 'Traditional unlimited thali with steamed rice, sambar, rasam, kootu, papad, pickle, buttermilk and payasam.',
      price: 250,
      category: 'meals',
      image: '/assets/tiffins-menu.jpg',
      isVeg: true,
      isSpicy: false,
      isPopular: true,
      isChefSpecial: false,
    },
    {
      id: 'ml-02',
      name: 'ప్రత్యేక భోజనం (Special Meals)',
      description: 'Premium thali featuring a daily-rotating special curry, ghee rice, appadam, two varieties of chutney and sweet.',
      price: 350,
      category: 'meals',
      image: '/assets/optimized-homepage.png',
      isVeg: true,
      isSpicy: false,
      isPopular: true,
      isChefSpecial: true,
    },
    {
      id: 'ml-03',
      name: 'గుండు భోజనం (Gundu Meals)',
      description: 'Hearty meals served in a traditional banana leaf with extra rice portions, pachadi and a fried special.',
      price: 300,
      category: 'meals',
      image: '/assets/homepage-screenshot.png',
      isVeg: true,
      isSpicy: true,
      isPopular: false,
      isChefSpecial: false,
    },
    {
      id: 'ml-04',
      name: 'బిర్యానీ భోజనం (Biryani Meals)',
      description: 'A complete combo of fragrant biryani paired with raita, mirchi ka salan and a serving of shrikhand.',
      price: 320,
      category: 'meals',
      image: '/assets/gallery-section.png',
      isVeg: true,
      isSpicy: true,
      isPopular: true,
      isChefSpecial: false,
    },
    {
      id: 'br-01',
      name: 'వేగ బిర్యానీ (Veg Biryani)',
      description: 'Aromatic basmati rice layered with garden-fresh vegetables, saffron and whole spices, slow-cooked in dum style.',
      price: 280,
      category: 'biryani',
      image: '/assets/gallery-section.png',
      isVeg: true,
      isSpicy: false,
      isPopular: true,
      isChefSpecial: false,
    },
    {
      id: 'br-02',
      name: 'పన్నీర్ బిర్యానీ (Paneer Biryani)',
      description: 'Tender paneer cubes marinated in yoghurt and spices, layered with fragrant rice and caramelised onions.',
      price: 320,
      category: 'biryani',
      image: '/assets/gallery-section.png',
      isVeg: true,
      isSpicy: true,
      isPopular: true,
      isChefSpecial: true,
    },
    {
      id: 'br-03',
      name: 'గుగ్గిలు బిర్యానీ (Mushroom Biryani)',
      description: 'Earthy button mushrooms and aromatic herbs folded into delicately spiced basmati rice.',
      price: 300,
      category: 'biryani',
      image: '/assets/gallery-section.png',
      isVeg: true,
      isSpicy: false,
      isPopular: false,
      isChefSpecial: false,
    },
    {
      id: 'br-04',
      name: 'తక్కలి బిర్యానీ (Tomato Biryani)',
      description: 'Tangy Hyderabadi-style tomato biryani with fresh mint, coriander and a hint of star anise.',
      price: 260,
      category: 'biryani',
      image: '/assets/gallery-section.png',
      isVeg: true,
      isSpicy: true,
      isPopular: false,
      isChefSpecial: true,
    },
    {
      id: 'br-05',
      name: 'పులావ్ (Veg Pulao)',
      description: 'Light and fluffy basmati rice tossed with mixed vegetables, whole garam masala and a drizzle of ghee.',
      price: 220,
      category: 'biryani',
      image: '/assets/optimized-homepage.png',
      isVeg: true,
      isSpicy: false,
      isPopular: false,
      isChefSpecial: false,
    },
    {
      id: 'bg-01',
      name: 'బగార బైంగన్ (Bagara Baingan)',
      description: 'Roasted baby aubergines simmered in a rich, nutty peanut-sesame gravy with tamarind and jaggery.',
      price: 240,
      category: 'bagara-specials',
      image: '/assets/homepage-mobile.png',
      isVeg: true,
      isSpicy: true,
      isPopular: true,
      isChefSpecial: true,
    },
    {
      id: 'bg-02',
      name: 'మిర్చి కా సలాన్ (Mirchi Ka Salan)',
      description: 'Stuffed chillies in a creamy coconut-peanut sauce — the quintessential Hyderabadi accompaniment to biryani.',
      price: 220,
      category: 'bagara-specials',
      image: '/assets/homepage-mobile.png',
      isVeg: true,
      isSpicy: true,
      isPopular: true,
      isChefSpecial: false,
    },
    {
      id: 'bg-03',
      name: 'గొబ్బు మంచూర్ (Cauliflower Manchurian)',
      description: 'Crispy cauliflower florets tossed in a tangy soy-chilli-garlic sauce with a sprinkle of spring onions.',
      price: 200,
      category: 'bagara-specials',
      image: '/assets/homepage-mobile.png',
      isVeg: true,
      isSpicy: true,
      isPopular: false,
      isChefSpecial: false,
    },
    {
      id: 'bg-04',
      name: 'పనీర్ బుట్ట మసాలా (Paneer Butter Masala)',
      description: 'Soft paneer cubes in a velvety tomato-butter gravy finished with cream and kasuri methi.',
      price: 260,
      category: 'bagara-specials',
      image: '/assets/homepage-mobile.png',
      isVeg: true,
      isSpicy: false,
      isPopular: true,
      isChefSpecial: false,
    },
    {
      id: 'bg-05',
      name: 'దాల్ తడ్కా (Dal Tadka)',
      description: 'Yellow lentils tempered with ghee, cumin, garlic and dried red chillies — soul food at its best.',
      price: 180,
      category: 'bagara-specials',
      image: '/assets/homepage-screenshot.png',
      isVeg: true,
      isSpicy: false,
      isPopular: false,
      isChefSpecial: false,
    },
    {
      id: 'bv-01',
      name: 'మజ్జిగ (Majjiga — Buttermilk)',
      description: 'Chilled churned buttermilk spiked with ginger, green chilli, curry leaves and a pinch of roasted cumin.',
      price: 60,
      category: 'beverages',
      image: '/assets/tiffins-menu.jpg',
      isVeg: true,
      isSpicy: false,
      isPopular: true,
      isChefSpecial: false,
    },
    {
      id: 'bv-02',
      name: 'మంచుపాలు (Badam Milk)',
      description: 'Warm almond milk infused with saffron, cardamom, rose water and slivers of pistachio and almond.',
      price: 120,
      category: 'beverages',
      image: '/assets/tiffins-menu.jpg',
      isVeg: true,
      isSpicy: false,
      isPopular: false,
      isChefSpecial: true,
    },
    {
      id: 'bv-03',
      name: 'మసాలా ఛాయ్ (Masala Chai)',
      description: 'House-blend Assam tea brewed with fresh ginger, cardamom, cinnamon and a splash of farm milk.',
      price: 50,
      category: 'beverages',
      image: '/assets/tiffins-menu.jpg',
      isVeg: true,
      isSpicy: false,
      isPopular: true,
      isChefSpecial: false,
    },
    {
      id: 'bv-04',
      name: 'లస్సీ (Sweet Lassi)',
      description: 'Thick and creamy yoghurt drink blended with sugar, cardamom and topped with a layer of fresh malai.',
      price: 100,
      category: 'beverages',
      image: '/assets/tiffins-menu.jpg',
      isVeg: true,
      isSpicy: false,
      isPopular: true,
      isChefSpecial: false,
    },
    {
      id: 'bv-05',
      name: 'ఫిల్టర్ కాఫీ (Filter Coffee)',
      description: 'Authentic South Indian filter coffee made with freshly ground dark roast beans and frothed milk.',
      price: 80,
      category: 'beverages',
      image: '/assets/tiffins-menu.jpg',
      isVeg: true,
      isSpicy: false,
      isPopular: true,
      isChefSpecial: false,
    },
    {
      id: 'ds-01',
      name: 'పాయసం (Payasam)',
      description: 'Traditional vermicelli payasam slow-cooked in milk, ghee, cashews, raisins and fragrant cardamom.',
      price: 120,
      category: 'desserts',
      image: '/assets/optimized-homepage.png',
      isVeg: true,
      isSpicy: false,
      isPopular: true,
      isChefSpecial: true,
    },
    {
      id: 'ds-02',
      name: 'గులాబ్ జామున్ (Gulab Jamun)',
      description: 'Golden, melt-in-mouth milk-solid dumplings soaked in warm rose-cardamom sugar syrup.',
      price: 100,
      category: 'desserts',
      image: '/assets/optimized-homepage.png',
      isVeg: true,
      isSpicy: false,
      isPopular: true,
      isChefSpecial: false,
    },
    {
      id: 'ds-03',
      name: 'బోండా మిఠాయి (Mysore Pak)',
      description: 'Crumbly, ghee-rich Gram flour fudge with a hint of cardamom — a Mysore classic.',
      price: 90,
      category: 'desserts',
      image: '/assets/optimized-homepage.png',
      isVeg: true,
      isSpicy: false,
      isPopular: false,
      isChefSpecial: true,
    },
    {
      id: 'ds-04',
      name: 'ద్వాదశ రసా (Double Ka Meetha)',
      description: 'Hyderabadi bread pudding soaked in reduced milk, flavoured with saffron, rose water and fried nuts.',
      price: 140,
      category: 'desserts',
      image: '/assets/optimized-homepage.png',
      isVeg: true,
      isSpicy: false,
      isPopular: false,
      isChefSpecial: false,
    },
  ],
  dailySpecialIds: ['ml-02', 'br-02', 'bg-01'],
};
